version: 0.2
env:
  variables:
    APP_NAME: "jf-portfolio-web"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm ci
  build:
    commands:
      - echo build process started now
      - npm run build
  terraform:
    commands:
      - echo "TODO - terraform"
  post_build:
    commands:
       # upload dist to s3
      - aws s3 sync ./dist/apps/web s3://jf-portfolio-web-$deploy_env/ --delete --acl public-read # --profile terraform
