version: 0.2
env:
  variables:
    APP_NAME: "jf-portfolio-web"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm ci
#  build:
#    commands:
#      - echo build process started now
#      - ng build --configuration=production
#  post_build:
#    commands:
#      - echo build process finished, we should uplload to S3 now
#      - cd dist/$APP_NAME
#      - ls -la
#      - aws s3 sync . s3://my-awsome-bucket-of-files --delete
